#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  6 13:55:39 2020

@author: mojtaba
"""

import numpy as np




# loading a file contains modified integers generated by mpiexm4.py 
group = np.loadtxt('group.csv', dtype='i', delimiter=',')

print(group)

# decoding the "random number" used in mpiexm4.py
count= 0
for i in range(len(group)-1):
    if group[i] == group[i+1]:
        count += 1
    else:
        count = 1

random_num = count

print('random number is equal to:',count)
        

