#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  6 13:55:39 2020

@author: mojtaba
"""
from mpi4py import MPI
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()


# loading a file contains modified integers generated by mpiexm4.py 
modified_int = int(np.loadtxt('data_'+str(rank)+'.txt', dtype='i'))
print(rank, modified_int)

group_of_int = comm.gather(modified_int, root=0)

# decoding the "random number" used in mpiexm4.py
if rank ==0:
    print('group of integers loaded from mpiexm4.py is:', group_of_int)

    count= 1
    for i in range(len(group_of_int)-1):
        if group_of_int[i] == group_of_int[i+1]:
            count += 1
        else:
            break

    random_num = count

    print('random number is equal to:',random_num)
        

